vaadin/base-starter-connect

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/2)

chore: add IDE-generated files to .gitignore 

---

README.md
e2e/index.spec.js
intern.json
package-lock.json
package.json

Fixes #5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/17)

Adding an integration test

---

pom.xml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/20)

Remove warnings in pom.xml

---

README.md
package.json
pom.xml

Fixes #10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/18)

Add maven task to run frontend tests

---

README.md
scripts/start/backend.js

Fixes #8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/21)

Fix start:backend not reloading when chained with start:frontend

---

README.md
pom.xml
scripts/start/backend.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/25)

Add Java file watchers

---

e2e/index.spec.js
frontend/index.html
frontend/index.js
package-lock.json
package.json

Closes #19
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/29)

Add vaadin-login

---

src/main/java/com/vaadin/connect/starter/GreeterService.java
src/main/java/com/vaadin/connect/starter/StarterApplication.java
src/main/java/com/vaadin/connect/starter/StarterOAuthConfiguration.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/35)

Remove Apache license headers

---

README.md
e2e/index.spec.js
package-lock.json
package.json
pom.xml
webpack.config.js

Fixes #11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/33)

Add client application to package

---

scripts/start/backend.js

Fixes #30
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/36)

fix: ensure graceful backend shutdown

---

e2e/index.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/44)

fix(tests): use pollUntil instead of fixed timeouts in tests

---

scripts/start/backend.js

Fix #45
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/50)

chore(script): show mvn build progress

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/54)

Make package.json license match repo license

---

eclipse/Start_Webpack_Watcher.launch

Needed after #49 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/55)

fix(launchers): fix npm task in frontend eclipse launcher

---

package.json
scripts/start/backend.js

* Revert #58 
* Use the fix from https://github.com/vaadin/vaadin-connect/pull/264
* Related discussion in [ slack ](https://vaadin.slack.com/archives/CDNTYMS9H/p1548062683000700)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/59)

chore(script): build frontend before starting the backend

---

package.json
src/main/resources/META-INF/resources/index.html

Fixes #63'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/65)

fix(devmode): assure that there is always an index.html file in place

---

pom.xml

Fixes #60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/66)

fix(devmode): do not install npm deps if already done.

---

pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/67)

fix(build): change phase to npm install in maven

---

package-lock.json
package.json
webpack.config.js

Fixes #53
Depends on DanielSchaffer/webpack-babel-multi-target-plugin#15
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/68)

feat(frontend): add livereload script in development mode

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/69)

fix(frontend): use fixed plugin version to prevent webpack error

---

intern.json
package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/71)

fix(e2e): disable Safari 12 for now, fix IE 11 startup

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/62)

chore(deps): update login component to an apache-licensed version

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/72)

fix(build): force themable mixin version

---

src/main/java/com/vaadin/connect/starter/StatusService.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/73)

fix the mismatch in Javadoc parameter name

---

src/main/resources/application.properties

Related to https://github.com/vaadin/vaadin-connect/pull/279
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/75)

Remove unused oauth parameters from application.properties

---

scripts/start/apibrowser.js

Fixes #89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/90)

fix the API browser (broken since v0.5.2)

---

e2e/index.spec.ts
frontend/env.d.ts
frontend/polyfills.ts
frontend/test/status-controller.spec.ts
frontend/test/utils.js
intern.json
package-lock.json
package.json
tsconfig.json

Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/88)

refactor: rewrite unit and e2e tests in TypeScript

---

frontend/index.html

(set the viewport size to 'device width')
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/92)

make the app look better on mobile

---

pom.xml
src/main/java/com/vaadin/connect/starter/StarterApplication.java

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/96)

 Update vaadin-connect to version 0.7.0

---

tsconfig.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/101)

feat: enable dynamic imports in TypeScript code

---

frontend/status-controller.ts
package.json
pom.xml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vaadin/base-starter-connect/102)

chore(build): update to vaadin-connect 0.9.0
